### ISSUE TITLE
balance loss weighting approaches

### ISSUE THREAD

**Issue by de-gozaru** [VICO-UoE/KD4MTL#2]
Hi,

Thank you for open-sourcing your code!

Among all the balance loss weighting techniques you tried (MGDA, gradnorm, etc), which one works the best from your experience?

Thank you in advance for your answer!

**Comment by WeihongLi-ac** [comment]
Hi,

Many thanks for your interests and question. We have updated the results of more loss weighting strategies in multi-task learning settings in our [Universal Representations](https://arxiv.org/pdf/2204.02744.pdf) paper. Probably you can check them out. The implementation of the latest version of our method and most existing loss balancing methods for MTL are available at https://github.com/VICO-UoE/UniversalRepresentations. We also included the implementation of the applications of our method to multi-domain learning and cross-domain learning. 

Hope this will help!
Thank you!

**Comment by de-gozaru** [comment]
Hi,

This answers my question, thank you for your help!

Best,
